"""add_buildings_refactor_rooms_add_faculty_id

Revision ID: 15338fde4568
Revises: a94a2d001bec
Create Date: 2026-04-21 22:10:40.607223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15338fde4568'
down_revision: Union[str, None] = 'a94a2d001bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('rooms', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('rooms', sa.Column('building_id', sa.Integer(), nullable=False))
    op.drop_constraint('rooms_university_id_fkey', 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'buildings', ['building_id'], ['id'])
    op.drop_column('rooms', 'university_id')
    op.add_column('users', sa.Column('faculty_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'faculties', ['faculty_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'faculty_id')
    op.add_column('rooms', sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key('rooms_university_id_fkey', 'rooms', 'universities', ['university_id'], ['id'])
    op.drop_column('rooms', 'building_id')
    op.drop_column('rooms', 'is_active')
    op.drop_table('buildings')
    # ### end Alembic commands ###
